sudo: false

language: go
go:
  - 1.8

before_install:
  - go get -u github.com/FiloSottile/gvt
  - go get github.com/mitchellh/gox
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - gvt restore
  - make ci
  - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN

before_deploy:
  - gox -os "linux darwin" -arch "386 amd64" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" ./cmd/kage/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false