[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.12.0"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "1.2.4"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/ryanuber/go-glob"
  version = "0.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "gopkg.in/alecthomas/kingpin.v2"

[[constraint]]
  name = "gopkg.in/inconshreveable/log15.v2"
  version = "2.11.0"
